Update update-smlocate
This update tries to cater for merging, as well as user-unique index files.  It works well on Linux, but is yet to be tested on other systems.

diff --git a/update-smlocate b/update-smlocate
--- a/update-smlocate
+++ b/update-smlocate
@@ -40,23 +40,29 @@ elif [ -d /var/tmp ]; then
   tmpDir=/var/tmp
 elif [ -d /usr/tmp ]; then
   tmpDir=/usr/tmp
-fi
-
-# This one can't be blank
-if [ -z "${tmpDir}" ]; then
+# We can't allow this variable to be blank
+else
   printf "%s\n" "[ERROR] - smlocate: Unable to determine the tmp directory on this system."
   exit 1
+fi
+
+# Now we need to set aside our own place to work
+tmpDir="${tmpDir}/smlocate"
+
+# Ensure the tmp directory exists
+if [ ! -d "${tmpDir}" ]; then
+  # If we can't create it, fail out
+  if ! mkdir -p "${tmpDir}" 2>/dev/null; then
+    printf "%s\n" "[ERROR] - smlocate: Unable to create '${tmpDir}', so unable to continue."
+    exit 1
+  fi
 fi
 
 ########################################
 # Cleanup function and traps
 cleanup() {
-  rm -f "${tmpDir}"/locate.merge
-  rm -f "${tmpDir}"/locate.user
-  rm -f "${tmpDir}"/locate.user.tmp
-  rm -f "${tmpDir}"/locate.root
-  rm -f "${tmpDir}"/locate.root.tmp
-} 2>/dev/null
+  find "${tmpDir}" -type f -name "locate.*" -exec rm -f {} \; 2>/dev/null
+} 
 
 # We want to trap on everything
 trap cleanup HUP INT QUIT TERM EXIT
@@ -71,6 +77,7 @@ if [ ! -d "${destDir}" ]; then
   if ! mkdir -p "${destDir}" 2>/dev/null; then
     destDir="${tmpDir}"
     # TO-DO: ensure correct permissions/ownership?
+    # TO-DO: Add notification?
   fi
 fi
 
@@ -79,14 +86,14 @@ fi
 # Try to keep it alphabetical if you add anything...
 exclFS="afs autofs coda ctfs dev devfs devpts fd ftpfs hsfs iso9660 lofs mfs mntfs namefs ncpfs nfs NFS objfs pcfs proc shfs smbfs sysfs tmpfs uvfs"
 
-# We convert this to a find friendly list
+# We convert this to a 'find' friendly list
 # We start by blanking out a new variable
 pruneFS=
 # Then for each item in the exclFS list, we build up the new variable
 for fs in ${exclFS}; do
   pruneFS="${pruneFS} -o -fstype ${fs}"
 done
-# Now we chop off the unwanted "-o" at the start of the variable
+# Now we chop off the unwanted '-o' at the start of the variable
 pruneFS=`echo "${pruneFS}" | cut -d " " -f3-`
 
 ########################################
@@ -98,7 +105,10 @@ pruneFS=`echo "${pruneFS}" | cut -d " " -f3-`
 # Slashes will be removed later on as well, so '/var/tmp' would become 'vartmp' which won't match anything
 exclPaths="/afs /amd /cdrom /media /proc /sfs /tmp"
 
-# We remove any slashes from exclPaths
+# We make an egrep filter for merging
+mergeExclPaths=`echo "${exclPaths}" | tr -d " " | sed 's/\//|\^\//g' | cut -d "|" -f2-`
+
+# And we remove any slashes from exclPaths for portable find usage
 exclPaths=`echo "${exclPaths}" | tr -d "/"`
 
 # Now we convert this to a list we can use in find.
@@ -112,11 +122,60 @@ for path in ${exclPaths}; do
 done
 
 ########################################
+# Figure out how we are going to run commands as 'nobody'
+suMethod=
+
+# First we test if "true" returns 0, if so we can go ahead with this style
+# This is theoretically the most portable option
+if su nobody -c "true" > /dev/null 2>&1; then
+  suMethod="su nobody -c"
+# Next, we try '-s', we use '-s' to override /bin/false or /bin/nologin i.e. (some) Solaris
+elif su nobody -s /bin/sh -c "true" > /dev/null 2>&1; then
+  suMethod="su nobody -s /bin/sh -c"
+# Next we try to cater for '-m' i.e. FreeBSD
+elif su -m nobody -c "true" > /dev/null 2>&1; then
+  suMethod="su -m nobody -c"
+# Otherwise, we fail out
+else
+  printf "%s\n" "[ERROR] - smlocate: Could not determine appropriate method to 'su' to user 'nobody'" \
+    "Unable to continue."
+  exit 1
+fi
+
+########################################
+# Declare our 'find' commands
+fullFind() {
+  if [ -z "$1" ]; then
+    searchPaths="${inclPaths}"
+  else
+    searchPaths="$1"
+  fi
+  # shellcheck disable=SC2086
+  find ${searchPaths} \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null
+}
+
+suFind() {
+  if [ -z "$1" ]; then
+    searchPaths="${inclPaths}"
+  else
+    searchPaths="$1"
+  fi
+  # shellcheck disable=SC2086
+  ${suMethod} "find ${searchPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print"
+}
+
+########################################
+# If we're not root, assign our username to a variable
+if [ ! -w / ]; then
+  myUserName=`whoami`
+fi
+
+########################################
 # Determine whether or not to use merging format
 # If 'false', the indexes will be completely rebuilt each time this update script is run
 # If 'true', only directories changed in the last 24 hours will be reindexed
 # For most basic usage, 'false' is safer.
-mergeIndex=false
+mergeIndex=true
 
 ################################################################################
 # No more editing should be necessary below this line
@@ -125,105 +184,81 @@ mergeIndex=false
 # If merging is enabled, we need to generate a list of directories
 # This builds an egrep filter that we apply to any existing index files
 if [ "${mergeIndex}" = true ]; then
-  filterDirs=""
-  find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -type d -mtime -1 -print 2>/dev/null > "${tmpDir}"/locate.merge
+ 
+  # Find all directories modified in the last 24 hours and generate a list file
+  # shellcheck disable=SC2086
+  find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -type d -mtime -1 -print 2>/dev/null \
+    | egrep -v "${mergeExclPaths}" | sed 's/^/\^/' > "${tmpDir}"/locate.merge
   
-  # shellcheck disable=SC2162
-  while IFS= read dir; do
-    filterDirs="|${dir}${filterDirs}"
-  done < "${tmpDir}"/locate.merge
-
-  # We no longer need the temporary file
-  rm -f "${tmpDir}"/locate.merge 2>/dev/null
-
-  # Now we chop off the unwanted "|" at the start of the variable
-  filterDirs=`echo "${filterDirs}" | cut -d "|" -f2-`
-
-  # We also generate a find friendly list
-  inclPaths=`echo "${filterDirs}" | tr "|" " "`
-
   # If the root index file exists and is writeable by us (i.e. we're root)...
-  # We filter out the modified directories from the current index
   if [ -w "${destDir}"/locate.root ]; then
-    egrep -v "${filterDirs}" "${destDir}"/locate.root > "${tmpDir}"/locate.root.tmp
-    # Now we reindex only those directories and append to the .tmp file
-    # shellcheck disable=SC2086
-    find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null >> "${tmpDir}"/locate.root.tmp
+    
+    # We create copies of the files to work on, using the merge list file
+    # as an input file for 'grep' to filter out the dirs to be reindexed
+    grep -v -f "${tmpDir}"/locate.merge "${destDir}"/locate.root > "${tmpDir}"/locate.root
+    grep -v -f "${tmpDir}"/locate.merge "${destDir}"/locate.user > "${tmpDir}"/locate.user
+    
+    # Now we need to remove the "^" from the start of each line in the merge file
+    sed 's/^\^//' < "${tmpDir}"/locate.merge > "${tmpDir}"/locate.merge2
+    mv "${tmpDir}"/locate.merge2 "${tmpDir}"/locate.merge
+    
+    # shellcheck disable=SC2162
+    while IFS= read dir; do
+      # shellcheck disable=SC2086
+      fullFind "${dir}" >> "${tmpDir}"/locate.root
+      # shellcheck disable=SC2086
+      suFind "${dir}" >> "${tmpDir}"/locate.user 2>/dev/null
+    done < "${tmpDir}"/locate.merge
 
-    # And finally move the .tmp file into place for the rest of the script
-    mv "${tmpDir}"/locate.root.tmp "${tmpDir}"/locate.root
-  fi
-  # And/or otherwise, act on the user index file
-  if [ -f "${destDir}"/locate.user ]; then
-    egrep -v "${filterDirs}" "${destDir}"/locate.user > "${tmpDir}"/locate.user.tmp
+  # If a file exists for your particular account, process it.
+  # Note: root invocations of this script will not update your individual index file
+  elif [ -f "${destDir}"/locate."${myUserName}" ]; then
+    # Obviously this find command will be limited to what you can access.
+    # Defying DRY practices here just saves a lot of headaches
+    grep -v -f "${tmpDir}"/locate.merge "${destDir}"/locate."${myUserName}" > "${tmpDir}"/locate."${myUserName}"
+    sed 's/^\^//' < "${tmpDir}"/locate.merge > "${tmpDir}"/locate.merge2
+    mv "${tmpDir}"/locate.merge2 "${tmpDir}"/locate.merge
+    # shellcheck disable=SC2162
+    while IFS= read dir; do
+      # shellcheck disable=SC2086
+      fullFind "${dir}" >> "${tmpDir}"/locate."${myUserName}"
+    done < "${tmpDir}"/locate.merge
     
-    # Create our user-readable file. This should remove most files that aren't 
-    # accessible to users, without needing to stat/test every file
-    # We need to figure out if 'su' requires '-s'.  This issue was found on, surprise: Solaris
-    # First we test if "true" returns 0, if so we can go ahead with this style
-    if su nobody -c "true" > /dev/null 2>&1; then
-      su nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null >> ${tmpDir}/locate.user.tmp"
-    # Next, we try '-s', we use '-s' to override /bin/false or /bin/nologin
-    elif su nobody -s /bin/sh -c "true" > /dev/null 2>&1; then
-      su nobody -s /bin/sh -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null >> ${tmpDir}/locate.user.tmp"
-    # Put in handling for FreeBSD
-    elif [ "`uname`" = FreeBSD ]; then
-      su -m nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print" >> ${tmpDir}/locate.user.tmp 2>/dev/null
-    # If nothing works, print a notification, then fail back to nothing and hope for the best
-    else
-      printf "%s\n" "[INFO] - smlocate: Unable to determine if 'su' on this host requires '-s /bin/sh'" \
-        "Proceeding on the assumption that it does not.  YMMV."
-      su nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null >> ${tmpDir}/locate.user.tmp"
-    fi
-    
-    mv "${tmpDir}"/locate.user.tmp "${tmpDir}"/locate.user
+  # If, however, the root index file doesn't exist (and we're root), we create it
+  elif [ ! -f "${destDir}"/locate.root ] -a [ -w / ]; then
+    fullFind > "${tmpDir}"/locate.root
+     
+  # And if the user index file doesn't exist (and we're root), we create it
+  elif [ ! -f  "${destDir}"/locate.user ] -a [ -w / ]; then
+    suFind > "${tmpDir}"/locate.user 2>/dev/null
   fi
 
 # Else, if merging is not enabled, we perform a full index.
+# If we're running as root, we can generate both files
+elif [ -w / ]; then
+  # Create our root-readable files
+  fullFind "${inclPaths}" > "${tmpDir}"/locate.root
+
+  # Now create our user-readable file.  See comments above.
+  suFind "${inclPaths}" > "${tmpDir}"/locate.user 2>/dev/null
+  
+# Otherwise, we just generate what we can (i.e. manual run)
+# This will list files limited to the invocating user
 else
-  ########################################
-  # If we're running as root, we can generate both files
-  if [ -w / ]; then
-    # Create our root-readable files
-    # shellcheck disable=SC2086
-    find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null > "${tmpDir}"/locate.root
-
-    # Now create our user-readable file.  See comments above.
-    if su nobody -c "true" > /dev/null 2>&1; then
-      su nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null > ${tmpDir}/locate.user"
-    elif su nobody -s /bin/sh -c "true" > /dev/null 2>&1; then
-      su nobody -s /bin/sh -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null > ${tmpDir}/locate.user"
-    elif [ "`uname`" = FreeBSD ]; then
-      su -m nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print" > ${tmpDir}/locate.user 2>/dev/null
-    else
-      printf "%s\n" "[INFO] - smlocate: Unable to determine if 'su' on this host requires '-s /bin/sh'" \
-        "Proceeding on the assumption that it does not.  YMMV."
-      su nobody -c "find ${inclPaths} \\( ${pruneFS}${prunePaths} \\) -prune -o -print 2>/dev/null > ${tmpDir}/locate.user"
-    fi
-
-  # Otherwise, we just generate what we can (i.e. manual run)
-  # This will list files limited to the invocating user
-  else
-    printf "%s\n" "[INFO] - smlocate: building index now, this may take a while..."
-    # Obviously if a merge file is there, we act appropriately
-    if [ -f "${tmpDir}"/locate.user.tmp ]; then
-      # shellcheck disable=SC2086
-      find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null >> "${tmpDir}"/locate.user.tmp
-      mv "${tmpDir}"/locate.user.tmp "${tmpDir}"/locate.user
-    else
-      # shellcheck disable=SC2086
-      find ${inclPaths} \( ${pruneFS}${prunePaths} \) -prune -o -print 2>/dev/null > "${tmpDir}"/locate.user
-    fi
-  fi
+  printf "%s\n" "[INFO] - smlocate: building index now, this may take a while..."
+  fullFind "${inclPaths}" > "${tmpDir}"/locate."${myUserName}"
 fi
 
 # Ensure correct ownership and permissions
 chown 0:0 "${tmpDir}"/locate.root 2>/dev/null
-chmod 440 "${tmpDir}"/locate.root 2>/dev/null
-chmod 444 "${tmpDir}"/locate.user
+chmod 600 "${tmpDir}"/locate.root 2>/dev/null
+chmod 444 "${tmpDir}"/locate.user 2>/dev/null
+chown "${myUserName}" "${tmpDir}"/locate."${myUserName}" 2>/dev/null
+chmod 600 "${tmpDir}"/locate."${myUserName}" 2>/dev/null
 
 # If tmpDir and destDir are different, move the tmp files to the destination
 if [ ! "${tmpDir}" = "${destDir}" ]; then
   mv "${tmpDir}"/locate.root "${destDir}"
   mv "${tmpDir}"/locate.user "${destDir}"
+  mv "${tmpDir}"/locate."${myUserName}" "${destDir}" 2>/dev/null
 fi
